use_frameworks!

target 'KATCircularProgressChart_Example' do
  pod 'KATCircularProgressChart', :path => '../'

  target 'KATCircularProgressChart_Tests' do
    inherit! :search_paths

    
  end
end
